### PR TITLE
fix for the organization metadata-add-description

### PR DESCRIPTION
**Pull request by pratik-vii**

### CODE REVIEW

**Comment by arturgontijo** [comment]
Hi @pratik-vii 
Could you please fix the `Organization Name:` issue in the `snet organization info` command with this PR too?
https://github.com/singnet/snet-cli/blob/master/packages/snet_cli/snet_cli/commands.py#L543

This line: https://github.com/singnet/snet-cli/blob/master/packages/snet_cli/snet_cli/commands.py#L539

Is not returning the Organization Name anymore, it's returning its `orgMetadataURI`.

**Comment by pratik-vii** [comment]
@arturgontijo Sure! I'll do it.

**Comment by pratik-vii** [comment]
@arturgontijo  It seems like it will take more time. The current change is blocker for other issue. I will raise another PR for suggested changes.

**Comment by arturgontijo** [comment]
Ok, cool!

**Pull request closed without merging**
