### PR TITLE
Logging, check organization and tags before publish/update

### PR DESCRIPTION
**Pull request by arturgontijo**
- Logging on every `transact()` call. (Related #61)
- `_service_json_parser()` checks if organization is valid and if user is a member|owner of it.
- Check the length of each tag (max 32 chars) before publish/update service.

### CODE REVIEW

**Comment by arturgontijo** [comment]
[bip32utils](https://pypi.org/project/bip32utils/) was removed from PyPI.
Its repo [GitHub/bip32utils](http://github.com/prusnak/bip32utils) was deleted...

**Comment by vsbogd** [comment]
@stellarspot  added issue https://github.com/singnet/snet-cli/issues/69

**Comment by vsbogd** [comment]
@arturgontijo , do you have time to look at issue #69? do you need help with it?

**Comment by arturgontijo** [comment]
I'm checking it right now.
I'll report my progress into #69 then.

**Pull request closed without merging**
