### PR TITLE
helper command to get network address of the contracts

### PR DESCRIPTION
**Pull request by prashantramangupta**
helper command to get the network address of the contracts(registry and mpe)

### CODE REVIEW

**Comment by prashantramangupta** [comment]
@astroseger pls review pr  **helper command to get network address of the contracts**

**Comment by astroseger** [comment]
@prashantramangupta 
Thanks for this PR. Welcome a board!
1. Next time, please refer original issue in your PR (in this case it would be https://github.com/singnet/snet-cli/issues/215)
2. I would propose to use ```camelCase``` for classes and ```simple_underscore_case``` for functions for sake of consistency with the rest of code base. 
3.  The situation is following: By default we read network addresses from "networks" jsons (from resources/contracts/networks). But user can overwrite these default network with ```snet set``` command by explicitly set current network address, or via command line arguments (see comments to ```get_contract_address``` in ```utils_config.py```).  The original proposition from #215 was to print these default network addresses, not the current addresses. 
4. It is not very beautiful to use ```BlockChainCommand``` inside ```SessionCommand```  (see  https://github.com/singnet/snet-cli/issues/159 where I propose to illuminate similar crutch). But I understand that if we want to have default network addresses in ```snet session``` we cannot do better without some redesign. 
 
I propose to do following:
1. Split SessionCommand into SessionSetCommand and SessionShowCommand. SessionShowCommand can be BlockChainCommand, so you don't need this dirty hack.
2. Extract from get_contract_address (utils.py) functionality for reading default network address (last part after line 29). So we will have function ```read_default_contract_address(w3, contract_name, error_message=None)```, and we will be able to use it in SessionShowCommand to show default contract addresses for the current network
3. Do not print error if you cannot read default network addresses, simply ```pass``` it.
4. Show also default contract address for ```singularityNetToken```

**Comment by astroseger** [comment]
@prashantramangupta could you separate health status commands in separate PR?

**Comment by astroseger** [comment]
I would propose to do the following: make two separate branches in your repository and open two separate PR from these two branches (and you close this PR!).

It is much more convenient to open PR from feature branches, not from master! And this situations is a very good example why...

In order two create two branches you can do the following:
```
git remote add singnet  https://github.com/singnet/snet-cli
git fetch singnet
git branch -m master current-work-branch

# it is better if you master is ALWAYS corresponds to singnet/master
git checkout -b master remotes/singnet/master

git checkout -b "helper-command-to-get-network-address-of-the-contracts"
git cherry-pick 805bd171fa1ec157a5c9a4c0885ba92620118e20
git checkout master
git checkout -b "getting-the-service-health-status"
git cherry-pick 3571d2b5123e6fcf12e43d11df7de7dfb61315c1
git cherry-pick ea5fa6b33c73427a2e2616f58ea3a1c95634989d

# now you close this PR and open two new PRs from branches: helper-command-to-get-network-address-of-the-contracts and getting-the-service-health-status
```

**Comment by prashantramangupta** [comment]
I have taken note. Work is in progress and I am closing this PR as of now.

**Pull request closed without merging**
