### PR TITLE
update grpc-tools version, fixes #243

### LINKED ISSUE #243: grpcio-health-checking version is incompatible with grpcio-tools
In setup.py

```
grpcio-health-checking==1.19.0
...
grpcio-tools==1.17.1
```

On running snet: `pkg_resources.DistributionNotFound: The 'grpcio>=1.19.0' distribution was not found and is required by grpcio-health-checking`

Fix is change `grpcio-tools==1.19.0`

### PR DESCRIPTION
**Pull request by ferrouswheel**

### CODE REVIEW

**Comment by ferrouswheel** [comment]
Confused as to why it failed :-/

**Comment by astroseger** [comment]
Interesting enough it has failed at ```snet service publish testo tests -y -q``` which doesn't contain explicit grpc calls (https://circleci.com/gh/singnet/snet-cli/247?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link).... But thanks god we have CI to catch such bugs..

@ferrouswheel will you investigate by yourself or do you need help with it?

**Comment by arturgontijo** [comment]
These days I'm not completely relying on CircleCI builds.
Check this build error:
https://circleci.com/gh/singnet/snet-cli/232

After that I've just re-build it and it got green. Maybe this is what happened here.

**Comment by astroseger** [comment]
Yes, restarting of build has helped.

**Comment by raamb** [comment]
Have seen this a couple of times where rebuild solved the problem. @prashantramangupta can you please pick this up on priority.

**Comment by astroseger** [comment]
should we merge it?

**Comment by ferrouswheel** [comment]
Yes please.

Got an email saying CircleCI have been having some growing pains lately https://status.circleci.com/ - not sure if related.

Another thing that might be worth doing is doing `--print-traceback` by default on all calls to `snet` in the integration tests. Would make it easier to understand what the issue if it's rare and sporadic

**Pull request merged**
